Feat 1
7th-avenue-closet/7th-avenue pull request #11
Opened 2024-06-12 12:16 UTC by JinkownHong

### 변경 사항
- Class: ReviewController, ReviewService, CreateReviewRequest, ReviewRepository, Rating
- createReview 기능 구현을 위해 다른 Domian의 일부 Class를 생성해놓은 부분 참고 부탁드립니다.

### 연관 이슈
- #1

2024-06-12 16:22 UTC, seungheyon commented on src/main/kotlin/com/example/backoffice/domain/product/review/service/ReviewService.kt
> +        val reviewer = userRepository.findByIdOrNull(userId)
user 클래스명을 바꾸는 것도 생각해 봐야 할 것 같습니다

2024-06-12 16:22 UTC, seungheyon commented
확인했습니다! 고생하셨습니당

2024-06-13 00:37 UTC, T0nixx requested changes

2024-06-13 00:37 UTC, T0nixx commented on src/main/kotlin/com/example/backoffice/domain/product/review/controller/ReviewController.kt
> +        @AuthenticationPrincipal user: User,
이 부분에서 AuthenticationPrincipal 로 쓰이는 user는 저 User를 import하면 안됩니다. 원래 코드에서 import 했던 부분을 보시면 아마 userdetails의 User일 거예요. 그리고 다른 principal 을 정의해서 쓸 예정입니다. 사실 처음부터 AuthenticationPrincipal을 넣어서 코드를 짜실 줄 몰라서 미리 말씀을 안드렸네요.
https://github.com/T0nixx/TodoAPI/blob/main/src/main/kotlin/com/teamsparta/todo/infra/security/dto/MemberPrincipal.kt 여기서 val oAuth2Provider: OAuth2Provider?가 빠진 형태가 될것 같아요.

2024-06-13 00:37 UTC, T0nixx commented on src/main/kotlin/com/example/backoffice/domain/product/review/model/Rating.kt
> +                throw InvalidObjectException("유효하지 않은 평점입니다, ONE부터 FIVE까지 하나를 입력해주세요!")
메시지 영어로 통일하기로 했었지않나요?ㅎㅎ

2024-06-13 00:37 UTC, T0nixx commented on src/main/kotlin/com/example/backoffice/domain/product/review/model/Review.kt
> +        private fun validateCommentLength(newComment: String) {
조건문을 확인하고 던지기만 하는(아무것도 리턴하지 않는) 경우에는 check나 ensure로 시작하는게 더 좋다는 피드백을 받았었어요. 어떻게 생각하세요?

2024-06-13 00:37 UTC, T0nixx commented on src/main/kotlin/com/example/backoffice/domain/product/review/model/Review.kt
>      var isDeleted: Boolean = false,
이거 deletedAt으로 각자 고치기로 했었나요 저희?

2024-06-13 00:37 UTC, T0nixx commented on src/main/kotlin/com/example/backoffice/domain/product/review/service/ReviewService.kt
> +        val reviewer = userRepository.findByIdOrNull(userId)
user:User가 principal: MemberPrincipal 로 바뀔 것 같아요. 그러면 굳이 바꾸지 않아도 괜찮을 것 같습니다

2024-06-13 00:37 UTC, T0nixx commented on src/main/kotlin/com/example/backoffice/domain/product/review/service/ReviewService.kt
> +        val (comment) = request
구조 분해 할당을 하는건 반복적으로 붙는 request. 을 없애기 위해서입니다. 그래서 만약 이 문법을 사용하신다면 val (comment, rating) = request 로 쓰셔서 28번 라인에 request.rating도 rating으로 바꾸시는게 좋아보여요. 그게 아니라면 그냥 request.comment request.rating으로 쓰는 것도 괜찮습니다. 아무튼 하나로 통일 해주시면 좋을 것 같아요.

2024-06-13 01:17 UTC, JinkownHong commented on src/main/kotlin/com/example/backoffice/domain/product/review/model/Rating.kt
> +                throw InvalidObjectException("유효하지 않은 평점입니다, ONE부터 FIVE까지 하나를 입력해주세요!")
해당 부분 바로 변경진행하겠습니다!

2024-06-13 01:20 UTC, JinkownHong commented on src/main/kotlin/com/example/backoffice/domain/product/review/model/Review.kt
> +        private fun validateCommentLength(newComment: String) {
넵 확인했습니다.

2024-06-13 05:47 UTC, taeaeaeae approved these changes
확인했습니다.

2024-06-13 07:36 UTC, T0nixx commented on src/main/kotlin/com/example/backoffice/domain/product/review/model/Review.kt
> +                throw InvalidObjectException("리뷰의 내용은 1자 이상 200자 이하로 작성해주세요!")
메시지 영어로 부탁드립니다

2024-06-13 08:01 UTC, closed without merging