feat getAllReviews, deleteReviewsByIds 메서드 Admin 내 구현
7th-avenue-closet/7th-avenue pull request #42
Opened 2024-06-14 10:58 UTC by JinkownHong

### 변경 사항
- UserId 를 통해 조회하고, 해당 유저의 모든 댓글들을 삭제할 수 있는 기능을 추가했습니다.

### 연관 이슈
- #28

2024-06-14 11:36 UTC, T0nixx requested changes

2024-06-14 11:36 UTC, T0nixx commented on src/main/kotlin/com/example/backoffice/domain/admin/service/AdminService.kt
> +            reviewIds != null -> reviewRepository.findAllById(reviewIds)
findByIdInAndDeletedAtIsNull 를 써서 조회 한다면 밑에서 deletedAt != null 을 할 필요가 없을 것 같아요

2024-06-14 11:36 UTC, T0nixx commented on src/main/kotlin/com/example/backoffice/domain/admin/service/AdminService.kt
> +            review.deletedAt = now
이것도 다른 entity 처럼 entity 안에서 함수를 통해 삭제되면 좋을 것 같네요

2024-06-14 11:36 UTC, T0nixx commented on src/main/kotlin/com/example/backoffice/domain/admin/service/AdminService.kt
> +        reviewRepository.saveAll(reviews)
dirty check가 제대로 된다면 saveAll이 따로 필요 없을 것 같은데 테스트 과정에서 문제가 있었나요?

2024-06-14 11:36 UTC, T0nixx commented on src/main/kotlin/com/example/backoffice/domain/admin/service/AdminService.kt
> +    fun deleteReviews( userId: Long?, reviewIds: List<Long>?) {
제가 처음 아까 좀 잘못 설명드렸던 것 같네요 제가 생각했던 흐름은 조회를 할 때 userId를 통해 조회할 수 있다면 getReviews(userId) 의 결과로 나온 List<reviewId> 를 다시 deleteReviews()의 인자로 쓰면 되니까 deleteReviews 에는 userId가 인자로 필요없을 것 같다는 말씀이었는데 어떻게 생각하세요? nullable한 인자가 두개 있는 건 좀 함수의 역할이 불분명해보여요

2024-06-14 11:36 UTC, T0nixx commented on src/main/kotlin/com/example/backoffice/domain/admin/service/AdminService.kt
> +        return if (userId != null) {
이 부분을 queryDSL을 사용하면 분기처리를 서비스에서 하지 않아도 돼서 비즈니스 로직을 한눈에 알아볼 수 있을 것 같아요 관심 있으시면 연습 겸 해보시는 것도 좋을 것 같아요

2024-06-14 11:36 UTC, T0nixx commented on src/main/kotlin/com/example/backoffice/domain/admin/controller/AdminController.kt
> +        @RequestParam userId: Long?,
서비스 쪽에 자세히 달아두었지만 reviewIds는 List<Long>으로 userId는 받지 않는 것이 좋아보입니다.

2024-06-14 11:36 UTC, T0nixx commented on src/main/kotlin/com/example/backoffice/domain/admin/controller/AdminController.kt
> +        return ResponseEntity.status(HttpStatus.OK).body(adminService.getReviews(userId))
admin인지에 대한 preAuthorize 과정이 필요할 것 같아요.

2024-06-14 11:36 UTC, T0nixx commented on src/main/kotlin/com/example/backoffice/domain/admin/controller/AdminController.kt
> +        adminService.deleteReviews(userId, reviewIds)
admin인지에 대한 preAuthorize 과정이 필요할 것 같아요.

2024-06-14 11:36 UTC, T0nixx commented on src/main/kotlin/com/example/backoffice/domain/product/review/dto/ReviewResponse.kt
> +    // val user: UserResponse
userId를 반환하지 않는 이유가 있을까요?

2024-06-14 11:36 UTC, T0nixx commented on src/main/kotlin/com/example/backoffice/domain/product/review/dto/ReviewResponse.kt
> +        productId = product.toResponse().id
product.id!!가 아니라 response 로 한번 변환해서 쓰는 이유가 있을까요?

2024-06-15 10:48 UTC, JinkownHong commented on src/main/kotlin/com/example/backoffice/domain/admin/service/AdminService.kt
> +        return if (userId != null) {
해당 부분은 추가로 이슈를 파서, 진행해보도록 하겠습니다 :)

2024-06-15 10:59 UTC, JinkownHong commented on src/main/kotlin/com/example/backoffice/domain/product/review/dto/ReviewResponse.kt
> +        productId = product.toResponse().id
Entity 값을 직접 내보내는 것보다 Dto 로 변환해서 나가는 것이 낫다가 생각을 했는데, 사실상 문제가 없을까요?

2024-06-16 12:14 UTC, closed without merging