feat: 상품 조건별 검색 및 페이지네이션
7th-avenue-closet/7th-avenue pull request #44
Opened 2024-06-14 11:35 UTC by taeaeaeae

### 변경 사항
- category별로 보기
- 이름, 최신순, 가격순 정렬
- name 검색
- 커서페이징
### 연관 이슈
- #30

2024-06-14 12:15 UTC, T0nixx requested changes

2024-06-14 12:15 UTC, T0nixx commented on src/main/kotlin/com/example/backoffice/domain/product/controller/ProductController.kt
> +        @RequestParam cursor: Long = 10,
cursor 의 기본값이 10인게 이상한 것 같아요 혹시 이유가 있을까요?

2024-06-14 12:16 UTC, T0nixx requested changes

2024-06-14 12:16 UTC, T0nixx commented on src/main/kotlin/com/example/backoffice/domain/product/repository/ProductRepositoryImpl.kt
> +        cursor.let { builder.and(product.id.gt(it)) }
이거 sorted 부분에 따라서 gt 인지 lt인지가 달라져야 할거예요

2024-06-14 12:18 UTC, T0nixx requested changes

2024-06-14 12:18 UTC, T0nixx commented on src/main/kotlin/com/example/backoffice/domain/product/repository/ProductRepositoryImpl.kt
> +            else -> product.id.desc()
"id.desc", "id.asc" 를 추가하고 else에서 throw를 하는게 나을 것 같은데 어떠신가요

2024-06-14 14:41 UTC, taeaeaeae commented on src/main/kotlin/com/example/backoffice/domain/product/repository/ProductRepositoryImpl.kt
> +            else -> product.id.desc()
처음얘기들었을땐 그게 나을것같다고 생각하고 코드 고치다가 생각해봤어요. 지금은 정렬을 저기서만 처리해서 아무것도 안들어왔을때 어차피 추가로 최신순으로 기본정렬을 따로 해야돼요 그래서 기본값 정렬을 하려고 else에 넣었던거같아요. 저기에 그대로 추가하면 null일 경우에도 throw를 하니까서 기본값으로 id.desc로 설정해두고 throw를 하겠습니다.

2024-06-14 15:03 UTC, taeaeaeae commented on src/main/kotlin/com/example/backoffice/domain/product/repository/ProductRepositoryImpl.kt
> +        cursor.let { builder.and(product.id.gt(it)) }
id.asc면 낮은거보여주는거로 수정했습니다.

2024-06-16 00:03 UTC, taeaeaeae commented on src/main/kotlin/com/example/backoffice/domain/product/controller/ProductController.kt
> +        @RequestParam cursor: Long = 10,
그냥 지웠어요

2024-06-16 10:49 UTC, T0nixx requested changes

2024-06-16 10:49 UTC, T0nixx commented on src/main/kotlin/com/example/backoffice/domain/product/repository/ProductRepositoryImpl.kt
> +        if (sorted != "id.asc") cursor.let { builder.and(product.id.gt(it)) }
이건 id일때만이 아니라 모든 sorted에 대해서 뒤에 값이 asc냐 desc냐에 따라 분기처리돼야 할 것 같아요

2024-06-16 10:49 UTC, T0nixx commented on src/main/kotlin/com/example/backoffice/domain/product/repository/ProductRepositoryImpl.kt
> +        if (sorted != "id.asc") cursor.let { builder.and(product.id.gt(it)) }
그리고 lt랑 gt가 반대로인 것 같은데 desc면 커서보다 작은 것 asc면 커서보다 큰 게 오는게 맞지 않나요?

2024-06-16 10:49 UTC, T0nixx commented on src/main/kotlin/com/example/backoffice/domain/product/repository/ProductRepositoryImpl.kt
> +        if (sorted != "id.asc") cursor.let { builder.and(product.id.gt(it)) }
이거 간단하게 이렇게 생각했었는데 문제가 좀 있네요 시간 되실 때 얘기를 나눠봐야할 것 같아요

2024-06-16 14:55 UTC, taeaeaeae commented on src/main/kotlin/com/example/backoffice/domain/product/repository/ProductRepositoryImpl.kt
> +        if (sorted != "id.asc") cursor.let { builder.and(product.id.gt(it)) }
우선 gt lt는 말씀하신게 훨씬 명료한것같아요 또 id일 때만이 아니라 다른 값으로 정렬했을 때는 시간 순서에 따른 정렬이 굳이 필요 없다고 느껴서 넣지 않기는 했는데 그럼 입력값으로 정렬하고 후에 시간순으로 정렬을 추가하면 될까요? 순서 정하는 함수에서는 기본값인 부분 컨트롤러에서 정해두지 않고 넣어둔 후에 아이디로 역순 조회 시에만 작용하지 않게 하면 괜찮을것같은데 어떤가요?

2024-06-17 00:30 UTC, T0nixx approved these changes

2024-06-17 00:30 UTC, merged